# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.1.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: ramcharancholleti@gmail.com
author_name: Ramcharan1706
preset_name: starter
project_name: reallestate-frontend

